services:
  elishama-db:
    image: postgres:15-alpine
    container_name: elishama-db
    environment:
      POSTGRES_DB: elishama_db
      POSTGRES_USER: elishama_user
      POSTGRES_PASSWORD: elishama_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elishama_user -d elishama_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elishama-network
    shm_size: 128mb
    mem_limit: 512m
    cpus: 1.0

  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: elishama-backend
    env_file: ./back-end/.env
    environment:
      - PRISMA_CLIENT_ENGINE_TYPE=binary
    depends_on:
      elishama-db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node src/index.js"
    networks:
      - elishama-network
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.0


  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: elishama-frontend
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/usr/src/app:cached
      - frontend_node_modules:/usr/src/app/node_modules
      - /usr/src/app/.react-router
      - /usr/src/app/build
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - elishama-network
    restart: unless-stopped
    mem_limit: 1536m  # 1.5 GB pour éviter ENOMEM
    cpus: 2.0

networks:
  elishama-network:
    driver: bridge

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules: